### ISSUE TITLE
Change ice update status display to communicate what generation of ice it was on, rather than before x updates.

### ISSUE THREAD

**Issue by TNTreee** [st-AR-gazer/_Wood-Warning#1]
Ice community has a naming convention of each ice physics version, which i think would be helpful to include in this plugin (even if as a togglable option).
game release -> oct 2022 update is Gen 1 ice
oct 22 update -> july 2023 update is Gen 2 ice
july 23 update -> current is Gen 3 ice

**Comment by st-AR-gazer** [comment]
Do you have any suggestions on what this could look like? Just some text that displays "Gen(eration) [number]"? Or something else?

**Comment by TNTreee** [comment]
Yes, text would work. Maybe could even replace the current spaghetti of warning message yourru have currently.

**Comment by st-AR-gazer** [comment]
but I like my spaghett...

Anyway, added 👍
