### ISSUE TITLE
add support for bumper change

### ISSUE THREAD

**Issue by ezio416** [st-AR-gazer/_Wood-Warning#2]
I don't remember exactly when the change was (and still don't know why it ever happened since there are still no vanilla bumper blocks), but it would be nice to know if a map is using old bumper physics

**Comment by ezio416** [comment]
If it helps, the newest map on TMX I could find that has broken bumpers is https://trackmania.exchange/maps/20921/sportyxd-16 which is build `2020-11-05_16_41`

Oldest map I can find with current bumper physics is https://trackmania.exchange/maps/22509/banamini-1 which is build `2020-12-22_13_18`

This still leaves uncertainty with at least build `2020-12-09_10_00`

**Comment by st-AR-gazer** [comment]
I had no clue there was a bumper change. Was it broken from the first nadeo patch? So, from build 0 to 2020-12-22-13-18? (Presumably, this build)

**Comment by ezio416** [comment]
Bumpers just used to be stronger, then Nadeo weakened their effect for some reason, and as a result there are maps that are not finishable so I say they're broken. They made this change some time in November/December, I just can't say exactly which patch it was, though I think I've narrowed it down to the two I listed above (unless there was another patch between builds Nov 5 and Dec 22)

**Comment by st-AR-gazer** [comment]
Yeah, that shouldn't be too hard to add :)
Now I just need a way to know if the map ACTUALLY has wood physics xdd

**Comment by st-AR-gazer** [comment]
Added 👍
